name: 'Vercel - Link a domain to a Vercel deployment'

inputs:
  vercel-token:
    description: 'The Vercel token'
    required: true
  vercel-organization-id:
    description: 'The Vercel organization id'
    required: true
  vercel-project-id:
    description: 'The Vercel project id'
    required: true
  domain:
    description: 'The domain that should be added'
    required: true
  url:
    description: 'The preview URL of a deployment'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Set Vercel organization id as environment variable
      run: echo "VERCEL_ORG_ID=${{ inputs.vercel-organization-id }}" >> $GITHUB_ENV
      shell: bash
    - name: Set Vercel project id as environment variable
      run: echo "VERCEL_PROJECT_ID=${{ inputs.vercel-project-id }}" >> $GITHUB_ENV
      shell: bash
    - name: Link the domain to preview URL
      working-directory: ${{ inputs.working-directory }}
      run: npx --yes vercel alias set --token=${{ inputs.vercel-token }} ${{ inputs.url }} ${{ inputs.domain }}
      shell: bash

