name: 'Vercel - Link a domain to a Vercel deployment'

inputs:
  vercel-token:
    description: 'The Vercel token'
    required: true
  vercel-scope:
    description: 'The Vercel scope'
    required: true
  deployment-domain:
    description: 'The deployment domain recieved from Vercel'
    required: true
  preview-domain:
    description: 'The custom preview domain that should be linked'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Disable telemetry
      working-directory: ${{ inputs.working-directory }}
      run: npx --yes vercel@50.8.1 telemetry disable
      shell: bash
    - name: Link the domain to preview URL
      working-directory: ${{ inputs.working-directory }}
      run: npx --yes vercel@50.8.1 alias set --scope=${{ inputs.vercel-scope }} --token=${{ inputs.vercel-token }} ${{ inputs.deployment-domain }} ${{ inputs.preview-domain }}
      shell: bash

