name: 'Vercel - Link a domain to a Vercel deployment'

inputs:
  vercel-token:
    description: 'The Vercel token'
    required: true
  vercel-scope:
    description: 'The Vercel scope'
    required: true
  domain:
    description: 'The domain that should be added'
    required: true
  url:
    description: 'The preview URL of a deployment'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Link the domain to preview URL
      working-directory: ${{ inputs.working-directory }}
      run: npx --yes vercel alias set --token=${{ inputs.vercel-scope }} --token=${{ inputs.vercel-token }} ${{ inputs.url }} ${{ inputs.domain }}
      shell: bash

